apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugabyte-operator
  namespace: yb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yugabyte-operator
  template:
    metadata:
      labels:
        name: yugabyte-operator
    spec:
      serviceAccountName: yugabyte-operator
      containers:
        - name: yugabyte-operator
          # Replace this with the built image name
          image: registry.connect.redhat.com/yugabytedb/yugabyte-operator:0.9.0-b2
          #image: nchandrappa/yb-operator:latest
          command:
            - yugabyte-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "yugabyte-operator"
